services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:29092,PLAINTEXT_HOST://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  # mongodb:
  #   image: mongo:7
  #   volumes:
  #     - mongo_data:/data/db

  gateway:
    build:
      context: .
      dockerfile: backend/gateway/Dockerfile
    image: autocrawl-gateway:latest
    depends_on:
      - user-service
      - bilibili-service
      - vnexpress-service
      - kafka
      - mongodb
    env_file:
      - .env
    environment:
      USER_SERVICE_URL: http://user-service:8030
      BILIBILI_SERVICE_URL: http://bilibili-service:8010
      KAFKA_BOOTSTRAP_SERVERS: kafka:29092
    ports:
      - "8000:8000"

  user-service:
    build:
      context: .
      dockerfile: backend/user_service/Dockerfile
    image: autocrawl-user-service:latest
    depends_on:
      - mongodb
    env_file:
      - .env
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:29092
    expose:
      - "8030"
    volumes:
      - social_profile_data:/app/social_profile

  bilibili-service:
    build:
      context: .
      dockerfile: backend/bilibili_service/Dockerfile
    image: autocrawl-bilibili-service:latest
    env_file:
      - .env
    environment:
      BILIBILI_SERVICE_URL: http://bilibili-service:8010
      GATEWAY_INTERNAL_EVENTS_URL: http://gateway:8000/api/internal/bilibili/events
      PUBLISHER_SERVICE_URL: http://publisher-service:8040
    expose:
      - "8010"
    volumes:
      - temp_data:/app/temp
      - data_demo:/app/data_demo

  vnexpress-service:
    build:
      context: .
      dockerfile: backend/vnexpress_service/Dockerfile
    image: autocrawl-vnexpress-service:latest
    env_file:
      - .env
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:29092
    expose:
      - "8020"

  publisher-service:
    build:
      context: .
      dockerfile: backend/publisher_service/Dockerfile
    image: autocrawl-publisher-service:latest
    env_file:
      - .env
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:29092
    expose:
      - "8040"
    volumes:
      - social_profile_data:/app/social_profile
      - temp_data:/app/temp
      - data_demo:/app/data_demo

volumes:
  # mongo_data:
  social_profile_data:
  temp_data:
  data_demo:
