"""v7_full_refactor

Revision ID: f7f1e3cc8d41
Revises: 
Create Date: 2026-08-23 23:57:02.914657
"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision = 'f7f1e3cc8d41'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_system_admin', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=120), nullable=False),
    sa.Column('target_type', sa.String(length=120), nullable=True),
    sa.Column('target_id', sa.String(length=120), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_actor_id'), 'audit_logs', ['actor_id'], unique=False)
    op.create_table('content_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('content_type', sa.String(length=40), nullable=False),
    sa.Column('canonical_title', sa.Text(), nullable=False),
    sa.Column('normalized_title', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('language', sa.String(length=12), nullable=False),
    sa.Column('content_scope', sa.String(length=40), nullable=False),
    sa.Column('owner_user_id', sa.UUID(), nullable=True),
    sa.Column('crawl_job_id', sa.UUID(), nullable=True),
    sa.Column('created_by_type', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('canonical_url', sa.Text(), nullable=True),
    sa.Column('content_hash', sa.String(length=128), nullable=True),
    sa.Column('transcript_hash', sa.String(length=128), nullable=True),
    sa.Column('quality_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('mongo_raw_id', sa.String(length=64), nullable=True),
    sa.Column('mongo_normalized_id', sa.String(length=64), nullable=True),
    sa.Column('sources_jsonb', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('media_jsonb', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('duplicate_count', sa.Integer(), nullable=False),
    sa.Column('story_id', sa.UUID(), nullable=True),
    sa.Column('episode_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['crawl_job_id'], ['crawl_jobs.id'], name='fk_content_item_crawl_job_id', ondelete='SET NULL', use_alter=True),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], name='fk_content_item_story_id', ondelete='SET NULL', use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_items_content_hash'), 'content_items', ['content_hash'], unique=False)
    op.create_index(op.f('ix_content_items_crawl_job_id'), 'content_items', ['crawl_job_id'], unique=False)
    op.create_index(op.f('ix_content_items_content_scope'), 'content_items', ['content_scope'], unique=False)
    op.create_index(op.f('ix_content_items_content_type'), 'content_items', ['content_type'], unique=False)
    op.create_index(op.f('ix_content_items_mongo_normalized_id'), 'content_items', ['mongo_normalized_id'], unique=False)
    op.create_index(op.f('ix_content_items_mongo_raw_id'), 'content_items', ['mongo_raw_id'], unique=False)
    op.create_index(op.f('ix_content_items_normalized_title'), 'content_items', ['normalized_title'], unique=False)
    op.create_index(op.f('ix_content_items_owner_user_id'), 'content_items', ['owner_user_id'], unique=False)
    op.create_index(op.f('ix_content_items_status'), 'content_items', ['status'], unique=False)
    op.create_index(op.f('ix_content_items_story_id'), 'content_items', ['story_id'], unique=False)
    op.create_index(op.f('ix_content_items_transcript_hash'), 'content_items', ['transcript_hash'], unique=False)
    op.create_table('crawl_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('crawl_mode', sa.String(length=40), nullable=False),
    sa.Column('content_scope', sa.String(length=40), nullable=False),
    sa.Column('created_by_type', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('current_stage', sa.String(length=40), nullable=False),
    sa.Column('priority', sa.SmallInteger(), nullable=False),
    sa.Column('total_discovered', sa.Integer(), nullable=False),
    sa.Column('total_crawled', sa.Integer(), nullable=False),
    sa.Column('total_normalized', sa.Integer(), nullable=False),
    sa.Column('total_failed', sa.Integer(), nullable=False),
    sa.Column('total_duplicates', sa.Integer(), nullable=False),
    sa.Column('progress_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('requested_by', sa.UUID(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crawl_jobs_content_scope'), 'crawl_jobs', ['content_scope'], unique=False)
    op.create_index(op.f('ix_crawl_jobs_requested_by'), 'crawl_jobs', ['requested_by'], unique=False)
    op.create_index(op.f('ix_crawl_jobs_status'), 'crawl_jobs', ['status'], unique=False)
    op.create_table('prompt_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('run_type', sa.String(length=60), nullable=False),
    sa.Column('reference_id', sa.UUID(), nullable=True),
    sa.Column('step_name', sa.String(length=80), nullable=False),
    sa.Column('model_provider', sa.String(length=80), nullable=True),
    sa.Column('model_name', sa.String(length=120), nullable=True),
    sa.Column('prompt_version', sa.String(length=80), nullable=True),
    sa.Column('input_reference', sa.String(length=255), nullable=True),
    sa.Column('output_reference', sa.String(length=255), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prompt_runs_reference_id'), 'prompt_runs', ['reference_id'], unique=False)
    op.create_index(op.f('ix_prompt_runs_run_type'), 'prompt_runs', ['run_type'], unique=False)
    op.create_index(op.f('ix_prompt_runs_status'), 'prompt_runs', ['status'], unique=False)
    op.create_index(op.f('ix_prompt_runs_user_id'), 'prompt_runs', ['user_id'], unique=False)
    op.create_table('social_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('platform', sa.String(length=40), nullable=False),
    sa.Column('profile_name', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('folder_path', sa.String(length=500), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('folder_path')
    )
    op.create_index(op.f('ix_social_profiles_platform'), 'social_profiles', ['platform'], unique=False)
    op.create_index(op.f('ix_social_profiles_status'), 'social_profiles', ['status'], unique=False)
    op.create_index(op.f('ix_social_profiles_user_id'), 'social_profiles', ['user_id'], unique=False)
    op.create_table('system_settings',
    sa.Column('key', sa.String(length=120), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('user_roles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    op.create_table('content_embeddings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('content_id', sa.UUID(), nullable=False),
    sa.Column('embedding', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('embedding_text', sa.Text(), nullable=False),
    sa.Column('model_name', sa.String(length=120), nullable=False),
    sa.Column('embedding_dim', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['content_id'], ['content_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('content_id', 'model_name', name='uq_content_embedding_model')
    )
    op.create_index(op.f('ix_content_embeddings_content_id'), 'content_embeddings', ['content_id'], unique=False)
    op.create_index(op.f('ix_content_embeddings_model_name'), 'content_embeddings', ['model_name'], unique=False)
    op.create_table('content_series',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('series_type', sa.String(length=60), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('current_part', sa.Integer(), nullable=False),
    sa.Column('total_parts', sa.Integer(), nullable=False),
    sa.Column('context_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['social_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_series_profile_id'), 'content_series', ['profile_id'], unique=False)
    op.create_index(op.f('ix_content_series_series_type'), 'content_series', ['series_type'], unique=False)
    op.create_index(op.f('ix_content_series_status'), 'content_series', ['status'], unique=False)
    op.create_index(op.f('ix_content_series_user_id'), 'content_series', ['user_id'], unique=False)
    op.create_table('crawl_job_sources',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('source_type', sa.String(length=40), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('keywords', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('configuration', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['crawl_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crawl_job_sources_job_id'), 'crawl_job_sources', ['job_id'], unique=False)
    op.create_index(op.f('ix_crawl_job_sources_source_type'), 'crawl_job_sources', ['source_type'], unique=False)
    op.create_table('kafka_tasks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('task_type', sa.String(length=60), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('current_stage', sa.String(length=80), nullable=True),
    sa.Column('progress_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('idempotency_key', sa.String(length=255), nullable=True),
    sa.Column('cancel_requested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('locked_by', sa.String(length=120), nullable=True),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('heartbeat_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('parent_task_id', sa.UUID(), nullable=True),
    sa.Column('reference_id', sa.UUID(), nullable=True),
    sa.Column('reference_type', sa.String(length=40), nullable=True),
    sa.Column('profile_id', sa.UUID(), nullable=True),
    sa.Column('payload_jsonb', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('result_jsonb', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['parent_task_id'], ['kafka_tasks.id'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['social_profiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_index(op.f('ix_kafka_tasks_reference_id'), 'kafka_tasks', ['reference_id'], unique=False)
    op.create_index(op.f('ix_kafka_tasks_status'), 'kafka_tasks', ['status'], unique=False)
    op.create_index(op.f('ix_kafka_tasks_task_type'), 'kafka_tasks', ['task_type'], unique=False)
    op.create_table('publishing_queue_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('content_id', sa.UUID(), nullable=True),
    sa.Column('article_link', sa.Text(), nullable=True),
    sa.Column('article_title', sa.Text(), nullable=False),
    sa.Column('platform', sa.String(length=40), nullable=False),
    sa.Column('generated_content', sa.Text(), nullable=True),
    sa.Column('ai_reason', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['content_id'], ['content_items.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['profile_id'], ['social_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_publishing_queue_items_content_id'), 'publishing_queue_items', ['content_id'], unique=False)
    op.create_index(op.f('ix_publishing_queue_items_profile_id'), 'publishing_queue_items', ['profile_id'], unique=False)
    op.create_index(op.f('ix_publishing_queue_items_scheduled_at'), 'publishing_queue_items', ['scheduled_at'], unique=False)
    op.create_index(op.f('ix_publishing_queue_items_status'), 'publishing_queue_items', ['status'], unique=False)
    op.create_index(op.f('ix_publishing_queue_items_user_id'), 'publishing_queue_items', ['user_id'], unique=False)
    op.create_table('social_posts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('post_url', sa.Text(), nullable=True),
    sa.Column('platform_post_id', sa.String(length=255), nullable=True),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['social_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_social_posts_profile_id'), 'social_posts', ['profile_id'], unique=False)
    op.create_table('social_profile_strategies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('content_topics', sa.Text(), nullable=False),
    sa.Column('avoid_topics', sa.Text(), nullable=False),
    sa.Column('tone', sa.String(length=255), nullable=False),
    sa.Column('target_audience', sa.String(length=255), nullable=False),
    sa.Column('post_frequency_per_day', sa.Integer(), nullable=False),
    sa.Column('active_hours', sa.String(length=120), nullable=False),
    sa.Column('schedule_enabled', sa.Boolean(), nullable=False),
    sa.Column('schedule_days', sa.String(length=40), nullable=False),
    sa.Column('schedule_times', sa.String(length=120), nullable=False),
    sa.Column('schedule_timezone', sa.String(length=80), nullable=False),
    sa.Column('approval_mode', sa.String(length=40), nullable=False),
    sa.Column('risk_level', sa.String(length=40), nullable=False),
    sa.Column('min_score', sa.Float(), nullable=False),
    sa.Column('require_video', sa.Boolean(), nullable=False),
    sa.Column('receive_system_content', sa.Boolean(), nullable=False),
    sa.Column('auto_project_queue_enabled', sa.Boolean(), nullable=False),
    sa.Column('video_render_mode', sa.String(length=40), nullable=False),
    sa.Column('max_system_recommendations', sa.Integer(), nullable=False),
    sa.Column('auto_queue_enabled', sa.Boolean(), nullable=False),
    sa.Column('auto_publish_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['social_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_social_profile_strategies_profile_id'), 'social_profile_strategies', ['profile_id'], unique=True)
    op.create_index(op.f('ix_social_profile_strategies_user_id'), 'social_profile_strategies', ['user_id'], unique=False)
    op.create_table('stories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('content_id', sa.UUID(), nullable=True),
    sa.Column('canonical_name', sa.Text(), nullable=False),
    sa.Column('normalized_name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('language', sa.String(length=12), nullable=False),
    sa.Column('total_episodes', sa.Integer(), nullable=False),
    sa.Column('completion_status', sa.String(length=40), nullable=False),
    sa.Column('grouping_confidence', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['content_id'], ['content_items.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stories_content_id'), 'stories', ['content_id'], unique=False)
    op.create_index(op.f('ix_stories_normalized_name'), 'stories', ['normalized_name'], unique=False)
    op.create_table('media_workflow',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('series_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('planning_mode', sa.String(length=40), nullable=True),
    sa.Column('primary_content_id', sa.UUID(), nullable=True),
    sa.Column('current_stage', sa.String(length=80), nullable=True),
    sa.Column('progress_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('draft_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('artifacts_jsonb', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('inputs_jsonb', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['primary_content_id'], ['content_items.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['profile_id'], ['social_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['series_id'], ['content_series.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_media_workflow_planning_mode'), 'media_workflow', ['planning_mode'], unique=False)
    op.create_index(op.f('ix_media_workflow_primary_content_id'), 'media_workflow', ['primary_content_id'], unique=False)
    op.create_index(op.f('ix_media_workflow_profile_id'), 'media_workflow', ['profile_id'], unique=False)
    op.create_index(op.f('ix_media_workflow_series_id'), 'media_workflow', ['series_id'], unique=False)
    op.create_index(op.f('ix_media_workflow_status'), 'media_workflow', ['status'], unique=False)
    op.create_index(op.f('ix_media_workflow_user_id'), 'media_workflow', ['user_id'], unique=False)
    op.create_table('planning_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('workflow_id', sa.UUID(), nullable=False),
    sa.Column('crawl_job_id', sa.UUID(), nullable=True),
    sa.Column('planning_mode', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('input_jsonb', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('output_jsonb', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('reason_jsonb', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['crawl_job_id'], ['crawl_jobs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['profile_id'], ['social_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workflow_id'], ['media_workflow.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_planning_runs_crawl_job_id'), 'planning_runs', ['crawl_job_id'], unique=False)
    op.create_index(op.f('ix_planning_runs_planning_mode'), 'planning_runs', ['planning_mode'], unique=False)
    op.create_index(op.f('ix_planning_runs_profile_id'), 'planning_runs', ['profile_id'], unique=False)
    op.create_index(op.f('ix_planning_runs_status'), 'planning_runs', ['status'], unique=False)
    op.create_index(op.f('ix_planning_runs_user_id'), 'planning_runs', ['user_id'], unique=False)
    op.create_index(op.f('ix_planning_runs_workflow_id'), 'planning_runs', ['workflow_id'], unique=False)
    op.create_table('planning_candidates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('planning_run_id', sa.UUID(), nullable=False),
    sa.Column('workflow_id', sa.UUID(), nullable=False),
    sa.Column('content_id', sa.UUID(), nullable=True),
    sa.Column('rank_order', sa.Integer(), nullable=True),
    sa.Column('score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('selected', sa.Boolean(), nullable=False),
    sa.Column('eligible', sa.Boolean(), nullable=False),
    sa.Column('reason_jsonb', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['content_id'], ['content_items.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['planning_run_id'], ['planning_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workflow_id'], ['media_workflow.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_planning_candidates_content_id'), 'planning_candidates', ['content_id'], unique=False)
    op.create_index(op.f('ix_planning_candidates_planning_run_id'), 'planning_candidates', ['planning_run_id'], unique=False)
    op.create_index(op.f('ix_planning_candidates_selected'), 'planning_candidates', ['selected'], unique=False)
    op.create_index(op.f('ix_planning_candidates_workflow_id'), 'planning_candidates', ['workflow_id'], unique=False)
    op.create_table('profile_content_links',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('content_id', sa.UUID(), nullable=True),
    sa.Column('story_id', sa.UUID(), nullable=True),
    sa.Column('relation_type', sa.String(length=60), nullable=False),
    sa.Column('relation_reason', sa.String(length=80), nullable=True),
    sa.Column('source_scope', sa.String(length=40), nullable=False),
    sa.Column('recommendation_status', sa.String(length=60), nullable=False),
    sa.Column('score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['content_id'], ['content_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['profile_id'], ['social_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profile_content_links_content_id'), 'profile_content_links', ['content_id'], unique=False)
    op.create_index(op.f('ix_profile_content_links_profile_id'), 'profile_content_links', ['profile_id'], unique=False)
    op.create_index(op.f('ix_profile_content_links_recommendation_status'), 'profile_content_links', ['recommendation_status'], unique=False)
    op.create_index(op.f('ix_profile_content_links_relation_reason'), 'profile_content_links', ['relation_reason'], unique=False)
    op.create_index(op.f('ix_profile_content_links_relation_type'), 'profile_content_links', ['relation_type'], unique=False)
    op.create_index(op.f('ix_profile_content_links_source_scope'), 'profile_content_links', ['source_scope'], unique=False)
    op.create_index(op.f('ix_profile_content_links_status'), 'profile_content_links', ['status'], unique=False)
    op.create_index(op.f('ix_profile_content_links_story_id'), 'profile_content_links', ['story_id'], unique=False)
    op.create_index(op.f('ix_profile_content_links_user_id'), 'profile_content_links', ['user_id'], unique=False)
    op.create_table('social_post_metrics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('post_id', sa.UUID(), nullable=False),
    sa.Column('views', sa.Integer(), nullable=False),
    sa.Column('likes', sa.Integer(), nullable=False),
    sa.Column('comments', sa.Integer(), nullable=False),
    sa.Column('shares', sa.Integer(), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['social_posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_social_post_metrics_captured_at'), 'social_post_metrics', ['captured_at'], unique=False)
    op.create_index(op.f('ix_social_post_metrics_post_id'), 'social_post_metrics', ['post_id'], unique=False)
    op.create_table('planning_feedback',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('media_workflow_id', sa.UUID(), nullable=False),
    sa.Column('feedback_type', sa.String(length=60), nullable=False),
    sa.Column('feedback_text', sa.Text(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['media_workflow_id'], ['media_workflow.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_planning_feedback_media_workflow_id'), 'planning_feedback', ['media_workflow_id'], unique=False)
    op.create_foreign_key(
        'fk_content_item_crawl_job_id',
        'content_items',
        'crawl_jobs',
        ['crawl_job_id'],
        ['id'],
        ondelete='SET NULL',
    )
    op.create_foreign_key(
        'fk_content_item_story_id',
        'content_items',
        'stories',
        ['story_id'],
        ['id'],
        ondelete='SET NULL',
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_content_item_story_id', 'content_items', type_='foreignkey')
    op.drop_constraint('fk_content_item_crawl_job_id', 'content_items', type_='foreignkey')
    op.drop_index(op.f('ix_planning_feedback_media_workflow_id'), table_name='planning_feedback')
    op.drop_table('planning_feedback')
    op.drop_index(op.f('ix_social_post_metrics_post_id'), table_name='social_post_metrics')
    op.drop_index(op.f('ix_social_post_metrics_captured_at'), table_name='social_post_metrics')
    op.drop_table('social_post_metrics')
    op.drop_index(op.f('ix_profile_content_links_user_id'), table_name='profile_content_links')
    op.drop_index(op.f('ix_profile_content_links_story_id'), table_name='profile_content_links')
    op.drop_index(op.f('ix_profile_content_links_status'), table_name='profile_content_links')
    op.drop_index(op.f('ix_profile_content_links_source_scope'), table_name='profile_content_links')
    op.drop_index(op.f('ix_profile_content_links_relation_type'), table_name='profile_content_links')
    op.drop_index(op.f('ix_profile_content_links_relation_reason'), table_name='profile_content_links')
    op.drop_index(op.f('ix_profile_content_links_recommendation_status'), table_name='profile_content_links')
    op.drop_index(op.f('ix_profile_content_links_profile_id'), table_name='profile_content_links')
    op.drop_index(op.f('ix_profile_content_links_content_id'), table_name='profile_content_links')
    op.drop_table('profile_content_links')
    op.drop_index(op.f('ix_media_workflow_user_id'), table_name='media_workflow')
    op.drop_index(op.f('ix_planning_candidates_workflow_id'), table_name='planning_candidates')
    op.drop_index(op.f('ix_planning_candidates_selected'), table_name='planning_candidates')
    op.drop_index(op.f('ix_planning_candidates_planning_run_id'), table_name='planning_candidates')
    op.drop_index(op.f('ix_planning_candidates_content_id'), table_name='planning_candidates')
    op.drop_table('planning_candidates')
    op.drop_index(op.f('ix_planning_runs_workflow_id'), table_name='planning_runs')
    op.drop_index(op.f('ix_planning_runs_user_id'), table_name='planning_runs')
    op.drop_index(op.f('ix_planning_runs_status'), table_name='planning_runs')
    op.drop_index(op.f('ix_planning_runs_profile_id'), table_name='planning_runs')
    op.drop_index(op.f('ix_planning_runs_planning_mode'), table_name='planning_runs')
    op.drop_index(op.f('ix_planning_runs_crawl_job_id'), table_name='planning_runs')
    op.drop_table('planning_runs')
    op.drop_index(op.f('ix_media_workflow_status'), table_name='media_workflow')
    op.drop_index(op.f('ix_media_workflow_series_id'), table_name='media_workflow')
    op.drop_index(op.f('ix_media_workflow_profile_id'), table_name='media_workflow')
    op.drop_index(op.f('ix_media_workflow_primary_content_id'), table_name='media_workflow')
    op.drop_index(op.f('ix_media_workflow_planning_mode'), table_name='media_workflow')
    op.drop_table('media_workflow')
    op.drop_index(op.f('ix_stories_normalized_name'), table_name='stories')
    op.drop_index(op.f('ix_stories_content_id'), table_name='stories')
    op.drop_table('stories')
    op.drop_index(op.f('ix_social_profile_strategies_user_id'), table_name='social_profile_strategies')
    op.drop_index(op.f('ix_social_profile_strategies_profile_id'), table_name='social_profile_strategies')
    op.drop_table('social_profile_strategies')
    op.drop_index(op.f('ix_social_posts_profile_id'), table_name='social_posts')
    op.drop_table('social_posts')
    op.drop_index(op.f('ix_publishing_queue_items_user_id'), table_name='publishing_queue_items')
    op.drop_index(op.f('ix_publishing_queue_items_status'), table_name='publishing_queue_items')
    op.drop_index(op.f('ix_publishing_queue_items_scheduled_at'), table_name='publishing_queue_items')
    op.drop_index(op.f('ix_publishing_queue_items_profile_id'), table_name='publishing_queue_items')
    op.drop_index(op.f('ix_publishing_queue_items_content_id'), table_name='publishing_queue_items')
    op.drop_table('publishing_queue_items')
    op.drop_index(op.f('ix_kafka_tasks_task_type'), table_name='kafka_tasks')
    op.drop_index(op.f('ix_kafka_tasks_status'), table_name='kafka_tasks')
    op.drop_index(op.f('ix_kafka_tasks_reference_id'), table_name='kafka_tasks')
    op.drop_table('kafka_tasks')
    op.drop_index(op.f('ix_crawl_job_sources_source_type'), table_name='crawl_job_sources')
    op.drop_index(op.f('ix_crawl_job_sources_job_id'), table_name='crawl_job_sources')
    op.drop_table('crawl_job_sources')
    op.drop_index(op.f('ix_content_series_user_id'), table_name='content_series')
    op.drop_index(op.f('ix_content_series_status'), table_name='content_series')
    op.drop_index(op.f('ix_content_series_series_type'), table_name='content_series')
    op.drop_index(op.f('ix_content_series_profile_id'), table_name='content_series')
    op.drop_table('content_series')
    op.drop_index(op.f('ix_content_embeddings_model_name'), table_name='content_embeddings')
    op.drop_index(op.f('ix_content_embeddings_content_id'), table_name='content_embeddings')
    op.drop_table('content_embeddings')
    op.drop_table('user_roles')
    op.drop_table('system_settings')
    op.drop_index(op.f('ix_social_profiles_user_id'), table_name='social_profiles')
    op.drop_index(op.f('ix_social_profiles_status'), table_name='social_profiles')
    op.drop_index(op.f('ix_social_profiles_platform'), table_name='social_profiles')
    op.drop_table('social_profiles')
    op.drop_index(op.f('ix_prompt_runs_user_id'), table_name='prompt_runs')
    op.drop_index(op.f('ix_prompt_runs_status'), table_name='prompt_runs')
    op.drop_index(op.f('ix_prompt_runs_run_type'), table_name='prompt_runs')
    op.drop_index(op.f('ix_prompt_runs_reference_id'), table_name='prompt_runs')
    op.drop_table('prompt_runs')
    op.drop_index(op.f('ix_crawl_jobs_status'), table_name='crawl_jobs')
    op.drop_index(op.f('ix_crawl_jobs_requested_by'), table_name='crawl_jobs')
    op.drop_index(op.f('ix_crawl_jobs_content_scope'), table_name='crawl_jobs')
    op.drop_table('crawl_jobs')
    op.drop_index(op.f('ix_content_items_transcript_hash'), table_name='content_items')
    op.drop_index(op.f('ix_content_items_story_id'), table_name='content_items')
    op.drop_index(op.f('ix_content_items_status'), table_name='content_items')
    op.drop_index(op.f('ix_content_items_owner_user_id'), table_name='content_items')
    op.drop_index(op.f('ix_content_items_normalized_title'), table_name='content_items')
    op.drop_index(op.f('ix_content_items_mongo_raw_id'), table_name='content_items')
    op.drop_index(op.f('ix_content_items_mongo_normalized_id'), table_name='content_items')
    op.drop_index(op.f('ix_content_items_content_type'), table_name='content_items')
    op.drop_index(op.f('ix_content_items_content_scope'), table_name='content_items')
    op.drop_index(op.f('ix_content_items_crawl_job_id'), table_name='content_items')
    op.drop_index(op.f('ix_content_items_content_hash'), table_name='content_items')
    op.drop_table('content_items')
    op.drop_index(op.f('ix_audit_logs_actor_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.drop_table('roles')
    # ### end Alembic commands ###
