import {
  DEFAULT_MAX_DURATION_SECONDS,
  applyJobFilter,
  applyJobSubtitles,
  cancelJob,
  createJobFromCandidate,
  createKeywordPlan,
  deleteJob,
  generateTikTokMetadata,
  getDeepSeekConfig,
  getPreviewUrl,
  getSeriesInfo,
  imageProxyUrl,
  listJobs,
  listTikTokProfiles,
  mediaUrl,
  openJobOutputFolder,
  publishJobToTikTok,
  retranslateJob,
  retryJob,
  searchCandidates,
  segmentUrl,
  translateTitle,
  updateDeepSeekConfig,
  mergeJobs,
  mergeParts
} from "@/features/bilibili/api";
import { subscribeBilibiliJobsSocket } from "@/features/bilibili/socketClient";
import type { VideoLocalizationSourceAdapter } from "@/features/video-localization/types";

export const bilibiliSource: VideoLocalizationSourceAdapter = {
  id: "bilibili",
  label: "Bilibili",
  defaultKeyword: "tổng tài ngôn tình",
  linkPlaceholder: "Nhập link Bilibili hoặc mã BV",
  sourceValue: "bilibili",
  defaultMaxDurationSeconds: DEFAULT_MAX_DURATION_SECONDS,
  listJobs,
  searchCandidates,
  createJobFromCandidate,
  deleteJob,
  cancelJob,
  retranslateJob,
  retryJob,
  applyJobSubtitles,
  applyJobFilter,
  mergeParts,
  mergeJobs,
  getDeepSeekConfig,
  updateDeepSeekConfig,
  translateTitle,
  createKeywordPlan,
  getPreviewUrl,
  getSeriesInfo,
  generateTikTokMetadata,
  listTikTokProfiles,
  publishJobToTikTok,
  openJobOutputFolder,
  mediaUrl,
  segmentUrl,
  imageProxyUrl,
  subscribeJobsSocket: subscribeBilibiliJobsSocket
};
